### ISSUE TITLE
polygon labeling

### ISSUE THREAD

**Issue by EvaMaeRey** [ggseg/ggseg#100]
Hello!  I'm an admirer of the ggseg package!  Thank you for the work on this.

I wondering if you'd think about supporting polygon labels?   I think the major change to geom_brain function would be that stat would need to be modified to stat = "sf_coordinates"?   

Just to try things out, tried using geom_sf and geom_sf labeling...  But I'm not sure how this would work in geom_brain or complementary function.  

aseg_df <- (aseg %>% as.data.frame())
ggplot() +
  aes(geometry = geometry, label = region) +
  geom_sf(data = aseg_df) + 
  geom_sf(data = aseg_df %>% filter(region == "amygdala"),
          fill = "darkred") + 
  geom_sf_text(data = aseg_df %>% filter(region == "amygdala"),
          fill = "darkred")

**Comment by drmowinckels** [comment]
We have an article about using the atlases with geom SF directly for this. Have a look at

https://ggseg.github.io/ggseg/articles/geom-sf.html
