### ISSUE TITLE
Significance lines

### ISSUE THREAD

**Issue by JenniferMosa** [ggseg/ggseg#51]
Hi! I am trying to change the thickness/colour of the ROIs that are statistically significant. The next code works, and the lines are thicker and red when the ROI is significant. However, it seems some of the ROIs are "behind" other structures, making the lines appear semi-covered. See for example cc-posterior (Hidden behind the cortex in grey), or the line of the left hippocampus in red, hidden behind the amygdala in blue. 

My question is, is there any way to change the "order" of the structures? In other words: the same way I change the colour and thickens, could I also make the most significant structures to be in the front so the lines don't become partly covered? 

```Rscript
## Create dataframe
DF <- aseg
DF$pval <- ifelse(!is.na(DF$region), seq(0, 0.1, length.out = 26), NA)

## Create columns for color and thickness based on the pvalue
cutoff_Pvalue = 0.05
DF$sig_col <- as.factor(ifelse(DF$pval>cutoff_Pvalue, "blue", "red"))
DF$sig_thick <- as.numeric(ifelse(DF$pval>cutoff_Pvalue, "1", "1.5"))

## Plot
DF %>%
  ggseg(atlas = "aseg",
        mapping = aes(
          fill = pval,
          colour = I(sig_col),
          size = I(sig_thick)
          ))
```

![Rplot](https://user-images.githubusercontent.com/76159643/102518722-eddc3780-4091-11eb-8d08-858754b36232.png)

**Comment by Athanasiamo** [comment]
Hi.

I'm afraid this is a little tricky request, as it would entail doing quite some wrangling of the atlas data. 
as per ggplot2 custom, to alter the order of how things are to plotted depends on the levels of the categorical data. If the data is in characters (as the atlas data are), they will be plotted in alphabetical order. So to alter the order, you'd need to make the region into a factor with the levels being the order you want things plotted in. 

Alternatively, you can update ggseg to the newest version, where you can utilise the new geom_brain, which plots with geom_sf and the order is a little different.


``` r
library(ggseg)
#> Loading required package: ggplot2

## Create dataframe
DF <- as.data.frame(aseg)
DF$geometry <- NULL
DF$pval <- ifelse(!is.na(DF$region), seq(0, 0.1, length.out = 26), NA)

## Create columns for color and thickness based on the pvalue
cutoff_Pvalue = 0.05
DF$sig_col <- as.factor(ifelse(DF$pval>cutoff_Pvalue, "blue", "red"))
DF$sig_thick <- as.numeric(ifelse(DF$pval>cutoff_Pvalue, ".5", "1"))


## Plot
ggseg(DF,
      atlas = aseg,
      mapping = aes(
        fill = pval,
        colour = I(sig_col),
        size = I(sig_thick)
      ))
#> merging atlas and data by 'atlas', 'type', 'hemi', 'region', 'side', 'label'
```

![](https://i.imgur.com/wVuCu40.png)

``` r


ggplot(DF) + 
  geom_brain(atlas = aseg, 
             aes(fill = pval, 
                 colour = I(sig_col),
                 size = I(sig_thick)))
#> merging atlas and data by 'atlas', 'type', 'hemi', 'region', 'side', 'label'
```

![](https://i.imgur.com/YffBC0y.png)

<sup>Created on 2021-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
