### ISSUE TITLE
Is it possible to set limits for 'ggseg' colour gradient?

### ISSUE THREAD

**Issue by emilyphedges** [ggseg/ggseg#56]
Hi, 

I am looking to visualise my imaging data using **ggseg**. To maintain consistency across all the images, it is possible to set the limits of the colour gradient where a value of 1.0 = green, 0.9 = yellow and 0.7 = red? I am hoping to ensure that any value less than 0.7 will remain red too. 

![ggseg-query](https://user-images.githubusercontent.com/84514660/119000560-2060c800-b983-11eb-86f8-82e1ba6590b8.png)

atlas_dk_aparcvolume1 <- ggseg(.data=atlas_dk_aparcvolume, atlas=dk, colour="white", mapping=aes(fill=vari)) +
    labs(fill="", subtitle = "cortical volume") +
    theme(legend.position = "right", legend.direction="vertical", legend.margin = margin(0, 0, 0, 0)) + 
    scale_fill_gradient2(low="red3",mid="goldenrod2",high="springgreen4", midpoint=0.9, na.value="grey")

Thank you!

**Comment by Athanasiamo** [comment]
Hi. 

This is a ggplot2 thing, not a ggseg thing. But you need to work a little more with the scaling function to get it working.
Below is an example. 
The biggest points are :
 - Set the limits of the colour scale, in addition to mid-point.
 - use "oob = scales::squish" to force all colours outside the bounds you have set to get the colour of the closest possible colour.

---
author: athanasm
date: 2021-05-20
output: "reprex::reprex\\_document"
title: used-aidi\_reprex.R
---

``` r
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(patchwork)

p1 <- diamonds %>% 
  filter(cut == "Ideal") %>% 
  ggplot(aes(x = price, y = depth)) +
  geom_jitter(aes(colour = carat))
p1
```

![](https://i.imgur.com/7OesaFF.png)

``` r
p2 <- diamonds %>% 
  filter(cut == "Fair") %>% 
  ggplot(aes(x = price, y = depth)) +
  geom_jitter(aes(colour = carat))
p2
```

![](https://i.imgur.com/jgM361z.png)

``` r

p1 / p2 +
  plot_layout(guides = "collect") &
  scale_colour_gradient2(low = "red3",
                       mid = "goldenrod2",
                       high = "springgreen4", 
                       midpoint = 0.9, 
                       limits = c(0.7, 1),
                       oob = scales::squish,
                       na.value = "grey")
```

![](https://i.imgur.com/5cz4uog.png)

<sup>Created on 2021-05-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by emilyphedges** [comment]
Thank you very much!
