### ISSUE TITLE
Package homepage link HTTP 404 error

### ISSUE THREAD

**Issue by bbrewington** [ggseg/ggseg#58]
When I clicked on the link for the package homepage (2021-05-25 7:49 AM EDT) it gave me an HTTP 404 error

https://lcbc-uio.github.io/ggseg/

**Comment by Athanasiamo** [comment]
Thank you! I'll be fixing that asap. I forgot the links when I moved it to its own github org.

**Comment by Athanasiamo** [comment]
fixed in #6dc9ee1424c86b6f456e839241b80f00a6ebdb1b
