### ISSUE TITLE
EEG 64 channel map

### ISSUE THREAD

**Issue by stedy** [ggseg/ggseg#59]
Not sure if this is appropriate for this package but someone suggested this grid at geofacet https://github.com/hafen/geofacet/issues/220 and it seems like it would be a better fit here.

**Comment by Athanasiamo** [comment]
Hi. 

We have not discussed if or how EEG channels could be incorporated here. But we might envision a way that could work. I personally dont have experience with EEG data, so I would need clear examples of what the expected look would be like, and also how people would use it. 

Note that we here display segmented brains, but gradients. And I've mostly seen gradients represented for EEG plots in papers? So this would not work here. 

I think perhaps eegUtils might be a better fit? 

https://www.mattcraddock.com/blog/2017/09/05/eegutils-an-r-package-for-eeg/

**Comment by stedy** [comment]
Thanks for the feedback
