### ISSUE TITLE
Issue with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [ggseg/ggseg#60]
Hi Athanasia

We are preparing the next ggplot2 release and our reverse dependency tests has showed an issue with ggdist. The issue revolves around a better check of the scale type in scale_colour_continuous() and related functions where it is now checked that what comes out of the type argument actually matches the aesthetic of the enclosing function. This change means that some of your examples and unit tests fails.

We hope to release the next version next week but this issue flew under my radar - let me know if it is possible to prepare a fix by then and if you need any help

best
Thomas

**Comment by Athanasiamo** [comment]
Hi Thomas.

Thanks for the heads up. Is this in the master branch of ggplot2 on github, or some other branch? Then I can grab it and adapt asap.

-- Mo

**Comment by thomasp85** [comment]
It is tracked on the v3.3.4-rc branch🙂

**Comment by Athanasiamo** [comment]
Hey @thomasp85 .

I just got to looking at this, as I've been ill a while. 
The errors to the scales are secondary to the errors I get from altered behaviour of geom_sf? Thats what its looking like on my end, and I am a little stumped at what is going on and why. 

I've had a piece of (not so pretty) but working solution to adding some default aesthetics to the geom when used, which currently seem to get stripped or not applied any more. At least I cannot see these in the data after the layer has been applied and the checks for required aesthetics are done by ggplot, anymore. 

https://github.com/ggseg/ggseg/blob/main/R/layer-brain.R#L58-L85


``` 
ggplot() + geom_brain(atlas = dk, geometry = geometry)
# Error in layer(geom = geom, stat = stat, data = data, mapping = mapping,  : 
  object 'geometry' not found 

ggplot() + geom_brain(atlas = dk, aes(geometry = geometry))
# produces plot
```

I'm not sure why these are not kept anymore, and any suggestion would be greatly appreciated.

**Comment by thomasp85** [comment]
This is because we have cleaned up the statefulness of layers so that `mapping` doesn't get altered after the first render - instead it is written to `computed_mapping` which you need to modify in your code

**Comment by Athanasiamo** [comment]
Thanks @thomasp85 ! your pointer lead me to fix the problems we had. Thanks a bunch for helping out!
