### ISSUE TITLE
Remapping coordinates into DK

### ISSUE THREAD

**Issue by bgunasekera** [ggseg/ggseg#64]
Hi,

I am unsure if this is an appropriate ask of ggseg.

Nevertheless, I have a list of coordinates (300+) I would like to parcellate across the DK atlas. Is this possible using ggseg? Ideally I would like to 'feed' ggseg the coordinates and the output is a list of DK brain regions

Best wishes,
Brandon

**Comment by didacvp** [comment]
Hi, 
I am afraid this is not suited to ggseg. ggseg uses rather arbitrary  coordinates system (useful for visualization purposes only) which do not correspond to any neuroimaging coordinate system such as MNI or Talairach. 

 

Best Regards, 

Didac

 

From: Brandon Gunasekera ***@***.***> 
Sent: Monday, August 2, 2021 5:17 PM
To: ggseg/ggseg ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggseg/ggseg] Remapping coordinates into DK (#64)

 

Hi,

I am unsure if this is an appropriate ask of ggseg.

Nevertheless, I have a list of coordinates (300+) I would like to parcellate across the DK atlas. Is this possible using ggseg? Ideally I would like to 'feed' ggseg the coordinates and the output is a list of DK brain regions

Best wishes,
Brandon

**Comment by bjgunasekera** [comment]
Dear Didac,

Many thanks for your response.

How about if I had a list of brain regions in the Gordon format for example. Would it be possible to 'relabel' them into DK? 

Best wishes,
Brandon

**Comment by didacvp** [comment]
Hi, 

I guess this should be possible but the relationship would not be one-to-one.


Since the Gordon atlas is purely cortical (am I correct?), it is quite straightforward to create a ggseg Gordon atlas if you are interested.

 

You could try to do it yourself, or you can send me the annotation and I will do it once I have spare time!

Best, 

Didac
