### ISSUE TITLE
Smith 2009 10 RSNs atlas

### ISSUE THREAD

**Issue by tongluobing** [ggseg/ggseg#73]
Hi,

ggseg is a great package. Is it possible to include the Smith 2009 10 RSNs template as the atlas of ggseg?

The template for the atlas is:
https://www.fmrib.ox.ac.uk/datasets/brainmap+rsns/

And, as introduced by Nilearn, they have incorporated Smith 2009 10 RSNs already:
https://nilearn.github.io/auto_examples/01_plotting/plot_prob_atlas.html#sphx-glr-auto-examples-01-plotting-plot-prob-atlas-py

Could this also be done by ggseg?

Thanks,
Jian

**Comment by tongluobing** [comment]
Hi!

Thanks for the explanation and hope ggseg can develop better and further.

Best,
--Jian

**Comment by zqsha** [comment]
Yes, completely understand the hard work of maintaining toolbox, hopefully add more well-known brain atlas (e.g. AAL90, Harvard-Oxford Atlas and etc..) in the future.

**Comment by Athanasiamo** [comment]
We already have quite some different atlases you might be interested in. 
Check out our r-universe for a complete list.

https://ggseg.r-universe.dev/ui#builds
