### ISSUE TITLE
Vertical stacking of lateral and medial hemispheres

### ISSUE THREAD

**Issue by daedhalus** [ggseg/ggseg#75]
Hi, is it possible in the position argument of ggseg with the dkextra atlas, to vertically stack the lateral and medial views of the hemispheres, so if I was to only visualize the left hemisphere, the final plot ideally would look something like this?
Thanks a lot :)
![ggseg_position](https://user-images.githubusercontent.com/85180790/139414870-f304ee00-26f8-4d9c-8b27-eea36b26774c.png)

**Comment by Athanasiamo** [comment]
Hi!

I'm afraid this is not possible. The dkextra atlas has limited functionality, as it is quite different from all our other atlases. We have not, and will likely not, spend time in developing custom pipelines to plot it like this.

Sorry for not being able to accommodate your wish.

**Comment by daedhalus** [comment]
Ok, I understand. Thank you for the quick reply!
