### ISSUE TITLE
Most efficient way to plot select ROIs from an atlas

### ISSUE THREAD

**Issue by neuropil** [ggseg/ggseg#76]
Hello Dr. Mowinckel,

Thank you for the incredible updates to this amazing plotting package!

Quick question (I apologize if this answer is in a current vignette), I was wondering what is the most efficient process for plotting a select set of ROIs from an atlas (not grouped or requiring a gradient color scheme)?

Thanks!
John

**Comment by Athanasiamo** [comment]
Do you mean something like this?

``` r
library(ggseg)
library(ggplot2)

data <- data.frame(
  region = brain_regions(dk)[1:3],
  reg_col = brain_regions(dk)[1:3]
)

data
#>                      region                   reg_col
#> 1                  bankssts                  bankssts
#> 2 caudal anterior cingulate caudal anterior cingulate
#> 3     caudal middle frontal     caudal middle frontal

ggplot(data) +
  geom_brain(atlas = dk,
             aes(fill = reg_col)) +
  scale_fill_brain2(dk$palette[data$region] )
#> merging atlas and data by 'region'
```

![](https://i.imgur.com/j3XMGxs.png)

<sup>Created on 2022-01-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by neuropil** [comment]
Yes! Perfect! Thank you!!
