### ISSUE TITLE
Assignment problem of "aseg" 

### ISSUE THREAD

**Issue by JinLiu1024** [ggseg/ggseg#78]
Hi, I ran into a problem in ggseg.
When I use the aseg atlas, I find that its "label" or "region" is different from the labels exported in freesurfer.
E.g.: For the list of tags in the template, I got 18 regions and 26 labels

```
library(ggseg)
aseg$data$label
```
 [1] <NA>                          <NA>                         
 [3] Left-Thalamus-Proper          Right-Thalamus-Proper        
 [5] Right-Lateral-Ventricle       Left-Hippocampus             
 [7] Left-Lateral-Ventricle        Right-Putamen                
 [9] Right-Amygdala                Left-Putamen                 
[11] Right-VentralDC               Left-VentralDC               
[13] Right-Hippocampus             Left-Amygdala                
[15] Left-Pallidum                 Right-Pallidum               
[17] Left-Caudate                  Right-Caudate                
[19] x3rd-ventricle                x4th-ventricle               
[21] brain-stem                    cc-anterior                  
[23] cc-central                    cc-mid-anterior              
[25] cc-mid-posterior              cc-posterior                 
[27] right-cerebellum-white-matter right-cerebellum-cortex      
[29] <NA>                         
26 Levels: brain-stem cc-anterior cc-central ... x4th-ventricle

```
  ggplot() +
  geom_brain(atlas = aseg,
             aes(fill = label))
```
![image](https://user-images.githubusercontent.com/60530815/155514329-3e90d16f-91fd-4c89-ad75-7f11afd17b88.png)

When I read data from "eg. table"(which was generated by asegstats2table ) using "read_freesurfer_table", I got 66 labels.

eg.table: 
```
library(ggseg)
seg <- read_freesurfer_table("G:/NPC_freesurfer/data/eg.table") 
seg$label
```
 [1] "Left-Lateral-Ventricle"        "Left-Inf-Lat-Vent"            
 [3] "Left-Cerebellum-White-Matter"  "Left-Cerebellum-Cortex"       
 [5] "Left-Thalamus-Proper"          "Left-Caudate"                 
 [7] "Left-Putamen"                  "Left-Pallidum"                
 [9] "X3rd-Ventricle"                "X4th-Ventricle"               
[11] "Brain-Stem"                    "Left-Hippocampus"             
[13] "Left-Amygdala"                 "CSF"                          
[15] "Left-Accumbens-area"           "Left-VentralDC"               
[17] "Left-vessel"                   "Left-choroid-plexus"          
[19] "Right-Lateral-Ventricle"       "Right-Inf-Lat-Vent"           
[21] "Right-Cerebellum-White-Matter" "Right-Cerebellum-Cortex"      
[23] "Right-Thalamus-Proper"         "Right-Caudate"                
[25] "Right-Putamen"                 "Right-Pallidum"               
[27] "Right-Hippocampus"             "Right-Amygdala"               
[29] "Right-Accumbens-area"          "Right-VentralDC"              
[31] "Right-vessel"                  "Right-choroid-plexus"         
[33] "X5th-Ventricle"                "WM-hypointensities"           
[35] "Left-WM-hypointensities"       "Right-WM-hypointensities"     
[37] "non-WM-hypointensities"        "Left-non-WM-hypointensities"  
[39] "Right-non-WM-hypointensities"  "Optic-Chiasm"                 
[41] "CC_Posterior"                  "CC_Mid_Posterior"             
[43] "CC_Central"                    "CC_Mid_Anterior"              
[45] "CC_Anterior"                   "BrainSegVol"                  
[47] "BrainSegVolNotVent"            "BrainSegVolNotVentSurf"       
[49] "lhCortexVol"                   "rhCortexVol"                  
[51] "CortexVol"                     "lhCerebralWhiteMatterVol"     
[53] "rhCerebralWhiteMatterVol"      "CerebralWhiteMatterVol"       
[55] "SubCortGrayVol"                "TotalGrayVol"                 
[57] "SupraTentorialVol"             "SupraTentorialVolNotVent"     
[59] "SupraTentorialVolNotVentVox"   "MaskVol"                      
[61] "BrainSegVol-to-eTIV"           "MaskVol-to-eTIV"              
[63] "lhSurfaceHoles"                "rhSurfaceHoles"               
[65] "SurfaceHoles"                  "EstimatedTotalIntraCranialVol"

When I need to map the values in different regions after analyzing the data, I get an error: 
[segp.csv](https://github.com/ggseg/ggseg/files/8132177/segp.csv)
```
figA <- segp %>%
  ggseg(atlas = "aseg",position = "stacked",mapping=aes(fill=p.adj))+
  labs(title = "p<0.05") + scale_fill_gradient(low = "blue", high = "white")
figA
```
merging atlas and data by 'label'
Warning: Some data not merged properly. Check for naming errors in data: CSF, 4th-Ventricle, Left-choroid-plexus, Left-Inf-Lat-Vent, 	Right-Inf-Lat-Vent, 3rd-Ventricle,...
Warning: Some data not merged. Check for spelling mistakes in CSF, 4th-Ventricle, Left-choroid-plexus, Left-Inf-Lat-Vent, 	Right-Inf-Lat-Vent, 3rd-Ventricle,...
![image](https://user-images.githubusercontent.com/60530815/155518774-fb8dc093-6347-4bb5-b5ed-95d3d6feefc1.png)

Obviously, not all significant values are drawn on the graph. I don't understand why these labels don't exist in aseg template. But when I plot using the plot (aseg) command, the labels are correct. All the labels I want to use are included.
 
![image](https://user-images.githubusercontent.com/60530815/155514484-d3dc1d80-2944-493e-90eb-d5b2618871c5.png)

Maybe you can help me solve this problem? Can the result in aseg$data$label be 45? Just like the displayed labels in plot(aseg).  
This supports the use of label perfect matching when drawing, so as to draw the picture I want. This problem has been bothering me for a long time, not sure if it is a problem with my tool usage. 
Anyway, looking forward to your reply.

Best Regards,
Wendy

**Comment by Athanasiamo** [comment]
Hi!

Sorry for replying so late, I totally missed this issue.

I've made an example fix below, but not for all your labels. Unforunately, we have some old labels in the atlas from when we initially started work on ggseg, which we should have fixed. The label column should indeed match the freesurfer output, but it does not sue to how we did things in the beginning. I'll make sure to put it on our todo to fix. So thank you for the bug report.

Below I have some code that will fix some labels, you'll need to add the rest needing fixing too. The labels must have the exact same names as the atlas.

``` r
library(ggseg)
#> Loading required package: ggplot2
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

seg <- read.table("~/Downloads/segp.csv", header = TRUE, sep=",") 
seg$label
#>  [1] "Left-Lateral-Ventricle"        "4th-Ventricle"                
#>  [3] "Brain-Stem"                    "Left-Hippocampus"             
#>  [5] "Left-Amygdala"                 "CSF"                          
#>  [7] "Left-Accumbens-area"           "Left-VentralDC"               
#>  [9] "Left-choroid-plexus"           "Right-Lateral-Ventricle"      
#> [11] "Left-Inf-Lat-Vent"             "Right-Inf-Lat-Vent"           
#> [13] "Right-Cerebellum-White-Matter" "Right-Cerebellum-Cortex"      
#> [15] "Right-Thalamus-Proper"         "Right-Caudate"                
#> [17] "Right-Putamen"                 "Right-Pallidum"               
#> [19] "Right-Hippocampus"             "Right-Amygdala"               
#> [21] "Right-Accumbens-area"          "Left-Cerebellum-White-Matter" 
#> [23] "Right-VentralDC"               "Right-choroid-plexus"         
#> [25] "WM-hypointensities"            "Left-Cerebellum-Cortex"       
#> [27] "Optic-Chiasm"                  "CC_Posterior"                 
#> [29] "CC_Mid_Posterior"              "CC_Central"                   
#> [31] "CC_Mid_Anterior"               "CC_Anterior"                  
#> [33] "Left-Thalamus-Proper"          "Left-Caudate"                 
#> [35] "Left-Putamen"                  "Left-Pallidum"                
#> [37] "3rd-Ventricle"

aseg_labs <- brain_labels(aseg) |> 
  as.character()
aseg_labs
#>  [1] "brain-stem"                    "cc-anterior"                  
#>  [3] "cc-central"                    "cc-mid-anterior"              
#>  [5] "cc-mid-posterior"              "cc-posterior"                 
#>  [7] "Left-Amygdala"                 "Left-Caudate"                 
#>  [9] "Left-Hippocampus"              "Left-Lateral-Ventricle"       
#> [11] "Left-Pallidum"                 "Left-Putamen"                 
#> [13] "Left-Thalamus-Proper"          "Left-VentralDC"               
#> [15] "Right-Amygdala"                "Right-Caudate"                
#> [17] "right-cerebellum-cortex"       "right-cerebellum-white-matter"
#> [19] "Right-Hippocampus"             "Right-Lateral-Ventricle"      
#> [21] "Right-Pallidum"                "Right-Putamen"                
#> [23] "Right-Thalamus-Proper"         "Right-VentralDC"              
#> [25] "x3rd-ventricle"                "x4th-ventricle"

# labels with differing naming.
idx <- which(!aseg_labs %in% seg$label)
aseg_labs[idx]
#>  [1] "brain-stem"                    "cc-anterior"                  
#>  [3] "cc-central"                    "cc-mid-anterior"              
#>  [5] "cc-mid-posterior"              "cc-posterior"                 
#>  [7] "right-cerebellum-cortex"       "right-cerebellum-white-matter"
#>  [9] "x3rd-ventricle"                "x4th-ventricle"

seg$label[!seg$label %in% aseg_labs]
#>  [1] "4th-Ventricle"                 "Brain-Stem"                   
#>  [3] "CSF"                           "Left-Accumbens-area"          
#>  [5] "Left-choroid-plexus"           "Left-Inf-Lat-Vent"            
#>  [7] "Right-Inf-Lat-Vent"            "Right-Cerebellum-White-Matter"
#>  [9] "Right-Cerebellum-Cortex"       "Right-Accumbens-area"         
#> [11] "Left-Cerebellum-White-Matter"  "Right-choroid-plexus"         
#> [13] "WM-hypointensities"            "Left-Cerebellum-Cortex"       
#> [15] "Optic-Chiasm"                  "CC_Posterior"                 
#> [17] "CC_Mid_Posterior"              "CC_Central"                   
#> [19] "CC_Mid_Anterior"               "CC_Anterior"                  
#> [21] "3rd-Ventricle"

seg <- seg |> 
  mutate(
    label = case_when(
      label == "4th-Ventricle" ~ "x4th-ventricle",
      label == "3rd-Ventricle" ~ "x3rd-ventricle",
      label == "Right-Cerebellum-Cortex" ~ "right-cerebellum-cortex",
      label == "Right-Cerebellum-White-Matter" ~ "right-cerebellum-white-matter",
      label == "Brain-Stem" ~ "brain-stem",
      label == "CC_Central" ~ "cc-central",
      label == "CC_Mid_Posterior" ~ "cc-mid-posterior",
      label == "CC_Anterior" ~ "cc-anterior",
      label == "CC_Posterior" ~ "cc-posterior",
      TRUE ~ label
    )
  )


seg %>%
  ggplot() +
  geom_brain(atlas = aseg,
             aes(fill=p.value)) +
  labs(title = "p<0.05") + 
  scale_fill_gradient(low = "blue", high = "white") +
  theme_brain2()
#> merging atlas and data by 'label'
#> Warning: Some data not merged properly. Check for naming errors in data:
#>    atlas type  hemi  region side  label        geometry     X   p.value
#>    <chr> <chr> <chr> <chr>  <chr> <chr>  <MULTIPOLYGON> <int>     <dbl>
#>  1 <NA>  <NA>  <NA>  <NA>   <NA>  CSF             EMPTY     6 0.0000763
#>  2 <NA>  <NA>  <NA>  <NA>   <NA>  Left-…          EMPTY     7 0.296    
#>  3 <NA>  <NA>  <NA>  <NA>   <NA>  Left-…          EMPTY     9 0.0000431
#>  4 <NA>  <NA>  <NA>  <NA>   <NA>  Left-…          EMPTY    11 0.000072 
#>  5 <NA>  <NA>  <NA>  <NA>   <NA>  Right…          EMPTY    12 0.000810 
#>  6 <NA>  <NA>  <NA>  <NA>   <NA>  Right…          EMPTY    21 0.190    
#>  7 <NA>  <NA>  <NA>  <NA>   <NA>  Left-…          EMPTY    22 0.127    
#>  8 <NA>  <NA>  <NA>  <NA>   <NA>  Right…          EMPTY    24 0.0392   
#>  9 <NA>  <NA>  <NA>  <NA>   <NA>  WM-hy…          EMPTY    25 0.0718   
#> 10 <NA>  <NA>  <NA>  <NA>   <NA>  Left-…          EMPTY    26 0.890    
#> 11 <NA>  <NA>  <NA>  <NA>   <NA>  Optic…          EMPTY    27 0.248    
#> 12 <NA>  <NA>  <NA>  <NA>   <NA>  CC_Mi…          EMPTY    31 0.0197
#> Warning: Some data not merged. Check for spelling mistakes in:
#>                            label  X     p.value
#> 30                          CSF  6 0.000076300
#> 31          Left-Accumbens-area  7 0.295927039
#> 32          Left-choroid-plexus  9 0.000043100
#> 33            Left-Inf-Lat-Vent 11 0.000072000
#> 34           Right-Inf-Lat-Vent 12 0.000809995
#> 35         Right-Accumbens-area 21 0.189882702
#> 36 Left-Cerebellum-White-Matter 22 0.126788385
#> 37         Right-choroid-plexus 24 0.039207846
#> 38           WM-hypointensities 25 0.071751065
#> 39       Left-Cerebellum-Cortex 26 0.890267561
#> 40                 Optic-Chiasm 27 0.247575075
#> 41              CC_Mid_Anterior 31 0.019679118
```

![](https://i.imgur.com/Jo7ylyK.png)

<sup>Created on 2022-05-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
