### ISSUE TITLE
Issues with cerebellum cortex label for aseg atlas

### ISSUE THREAD

**Issue by elisaguma** [ggseg/ggseg#80]
Hi there, I am using your wonderful tool to plot my subcortical Freesurfer results and came across an issue.

For the Region, "cerebellum cortex", in the sagittal view, the corresponding label is "right-cerebellum-white-matter", whereas for the region "cerebellum white matter", again in the sagittal view, the corresponding label is "right-cerebellum-cortex". This seems in correct to me, and I can work around it by relabeling my results when i `brain_join` my results, however, this is likely to cause errors and confusion.

Is there any way this can be fixed?

Thanks so much :)

**Comment by Athanasiamo** [comment]
Hi!

This is absolutely a bug from our side. I'll get to patching it once I get the time. But its not going to be for another few weeks at least, so keep doing your work around, and I'll notify here when its fixed in the development version at least.
