### ISSUE TITLE
Applying ggseg to draw an image of some specific brain regions

### ISSUE THREAD

**Issue by jenhungwang2019** [ggseg/ggseg#86]
Dear Dr. Mowinckel,
Good day.
I used to write to you about applying ggseg to draw an image of the Default Mode Network (DMN) around two years ago.
Now, I faced another problem.
I wonder if ggseg could create an image of a brain via highlighting some regions of interest only?
The regions include putamen, caudate nucleus, thalamus, globus pallidus, nucleus accumbens, amygdala, and hippocampus.
How can I do that via using the 'ggseg' package?
Thanks.

**Comment by drmowinckels** [comment]
So you mean something like this, just for the aseg atlas?
https://github.com/ggseg/ggseg/issues/76

**Comment by jenhungwang2019** [comment]
Thanks for your help.
