### ISSUE TITLE
Highlighting according to effect

### ISSUE THREAD

**Issue by rskl92** [ggseg/ggseg#87]
Hi,

Instead of highlighting regions based on p-values, I would like to highlight the "significant" (p<0.05) regions according to the beta (e.g. negative- blue and positive-red). Has this been done before? I couldn't find it on the tutorial.

Thanks

**Comment by drmowinckels** [comment]
Hi!

Have a look at the ggplot tutorial on scales for ggplot. These work for ggseg too, as its a ggplot2 extention.

https://ggplot2-book.org/scale-colour.html
