### ISSUE TITLE
Highlighting different regions across different life stages

### ISSUE THREAD

**Issue by rskl92** [ggseg/ggseg#88]
[brain_vis_dk_thickness.xlsx](https://github.com/ggseg/ggseg/files/9734016/brain_vis_dk_thickness.xlsx)
Hi, 

I am trying to visualise the significant regions across different life stages represented by group. However, the brains all look blue in all regions

thick %>%
  group_by(groups) %>%
  ggplot() +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = b)) +
  facet_wrap(~groups)
#> merging atlas and data by 'region

Any advice would be super appreciated!
Thanks

**Comment by drmowinckels** [comment]
Hi!

This is not possible for me to debug without seeing the data that goes in (i.e. the `thick` object).

Do the examples of grouped output work for you?

``` r
library(ggseg)
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

someData <- tibble(
  region = rep(c("transverse temporal", "insula",
                 "precentral","superior parietal"), 2), 
  p = sample(seq(0,.5,.001), 8),
  groups = c(rep("g1", 4), rep("g2", 4))
)

someData %>%
  group_by(groups) %>%
  ggplot() +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = p)) +
  facet_wrap(~groups) +
  ggtitle("correct facetting")
#> merging atlas and data by 'region'
```

![](https://i.imgur.com/vP3Ngh7.png)

<sup>Created on 2022-10-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
