### ISSUE TITLE
trouble getting dataset to plot using ggseg ("Error in FUN(X[[i]], ...) : object '.id' not found")

### ISSUE THREAD

**Issue by vanessambrown** [ggseg/ggseg#89]
Hi, I just discovered this package and am very thankful to the developers for making such a great tool! 

I am getting the following issue when I try to plot my data: "Error in FUN(X[[i]], ...) : object '.id' not found". 

I saw this error in issue #15, and I have confirmed that I can plot dummy data using ggseg(). I have also used atlas=ggseg::dk to make sure there are no other packages interfering. I am using data files that have been altered (to check for and remove outliers) from the original freesurfer output, so I wonder if something is set up wrong with my input data.

This is the command that returns the error:
```
ggseg(data=m1_group_DNA_ME_cort,mapping=aes(fill=t_value),atlas=ggseg::dk)
```

Here is a snippet of my data: 
```
head(m1_group_DNA_ME_cort)
# A tibble: 6 × 6
  estimate    SE     df t_value  p_value label                     
     <dbl> <dbl>  <dbl>   <dbl>    <dbl> <chr>                     
1   0.615  0.178 19112.   3.45  0.000554 lh_bankssts               
2   0.0389 0.180 19112.   0.216 0.829    lh_caudalanteriorcingulate
3   0.0284 0.179 19112.   0.159 0.874    lh_caudalmiddlefrontal    
4   0.123  0.178 19112.   0.691 0.490    lh_cuneus                 
5   0.269  0.179 19112.   1.50  0.133    lh_entorhinal             
6  -0.126  0.178 19112.  -0.704 0.481    lh_frontalpole  
```       
and I have confirmed that the label names match the dk atlas:
```
m1_group_DNA_ME_cort$label %in% as.data.frame(ggseg::dk)$label
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[22] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[43] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[64] TRUE TRUE TRUE TRUE TRUE
```

Is there something I am missing with formatting my data?

**Comment by vanessambrown** [comment]
update: I am still getting the same error with the above ggseg command, but it does plot correctly using ggplot+geom_brain:
```
ggplot(m1_group_DNA_ME_cort)+geom_brain(aes(fill=t_value),atlas=dk)
```
Any idea why it works using ggplot+geom_brain and not ggseg?

**Comment by drmowinckels** [comment]
I'm not entirely sure what is going on, but is there a specific reason you want to rather use `ggseg()` than the `ggplot() + geom_brain()` combo? `ggseg()` is being soft-deprecated, so I'm not actively maintaining it,.

**Comment by vanessambrown** [comment]
Ah,  I didn't realize that ggseg was being soft-deprecated - now that I have ggplot() + geom_brain() working, things are fine on my end. Thanks!
