### ISSUE TITLE
There's something wrong in my aseg code..

### ISSUE THREAD

**Issue by lsmtgr** [ggseg/ggseg#97]
Hello !
This is my R code

brain <- tibble(  region = c("thalamus proper", "putamen", "caudate", "pallidum", "hippocampus", 
"amygdala"),  
p = c("0.00022", "0.0262", "0.000945", "8.6E-04", "6.3E-03", "0.006093"),
)

brainx <- brain %>% filter(p < 0.05)
ggplot(brainx) + geom_brain(atlas = aseg, side = "coronal", hemi = "left", aes(fill = p)) + 
scale_fill_viridis_c(option = "cividis", direction = -1) +  
theme_void() +
labs(title = "R basal")

![image](https://github.com/ggseg/ggseg/assets/159910365/6b7fac9e-b4ee-48c0-b4f2-7ead7d9816bb)

**"An error message similar to the image above appeared. What might be wrong?"**

**Comment by drmowinckels** [comment]
Hi!

The error message is saying that you are trying to apply a continuous scale to a discrete value. 

You've entered the p values with quotes, meaning R thinks they are a categorical scale. Unquote your numbers and everything should be fine.

This is not a ggseg specific thing, but ggplot2.

https://stackoverflow.com/questions/29278153/plotting-with-ggplot2-error-discrete-value-supplied-to-continuous-scale-on-c

**Comment by lsmtgr** [comment]
Thank you very much ! It works !!!!!!!!
