### ISSUE TITLE
Maybe It is my last question about ggseg atlas .. about P-value gradient solid bar

### ISSUE THREAD

**Issue by lsmtgr** [ggseg/ggseg#98]
Hello everyone !

I've encountered some problem..
Here's my latest R code a/w aseg atlas

brain <- tibble( region = c("thalamus proper", "putamen", "caudate", "pallidum", "hippocampus",
"amygdala"),
p = c(0.00022, 0.0262, 0.000945, 8.6E-04, 6.3E-03, 0.006093),
)

brainx <- brain %>% filter(p < 0.05)
ggplot(brainx) + geom_brain(atlas = aseg, side = "coronal", hemi = "left", aes(fill = p)) +
scale_fill_viridis_c(option = "cividis", direction = -1) +
theme_void() +
labs(title = "R basal")

![image](https://github.com/ggseg/ggseg/assets/159910365/52b039d1-f71f-4d4d-867b-b5131fb8e1f9)

If you look at the above two figures, you can see the p-value gradient bar is assigned automatically based on the values of p.

However, I want to fix the p-value bar to an absolute number like the blue p-value bar below. How should I modify the code?
Thank you for your precious opinion..

**Comment by drmowinckels** [comment]
Hi!

This is something ggplots scaling (in this case the film function) deals with. You can pass it the limits argument with a vector of two numbers, the minimum value and maximum value of your wanted scale. This will fix it to what you want it to be.

https://ggplot2.tidyverse.org/reference/continuous_scale.html
